### ISSUE TITLE
Consecutive $ characters are reduced to a single $

### ISSUE THREAD

**Issue by julianlam** [psychobunny/templates.js#43]
This bug is confirmed on NodeBB, but unconfirmed as being caused by templates.js.

Please see the following issue for comment: julianlam/nodebb-plugin-markdown#45

**Comment by psychobunny** [comment]
somebody reposted here: https://github.com/NodeBB/NodeBB/issues/4061

https://github.com/psychobunny/templates.js/commit/a9b7e7b45637b1869f9029e1fa094e4ad7218d05

^ test that has consecutive `$`, passes for me, so might be something in core

**Comment by barisusakli** [comment]
Maybe try the test with this content
```
<p><code>unix:DEFINES += VERSION=\\\\\\&quot;$$VERSION\\\\\\&quot;</code>\n
```

Since thats what the api returns

**Comment by frissdiegurke** [comment]
@barisusakli @psychobunny I've done some tests on this and it IS a `templates.js` related bug.
It does only occur within repeated arrays thought:
```
templates.parse("<!-- BEGIN posts -->$$$<!-- END posts -->", {posts: [{}]});
// "$"
```

**Comment by barisusakli** [comment]
Ahh thanks @frissdiegurke I was trying to repro this for a while but couldn't

**Comment by psychobunny** [comment]
oh nice. thanks for the repro steps friss

**Comment by frissdiegurke** [comment]
no problem, I saw @barisusakli commenting around this and got interested if an additional pair of eyes could help ;-)

**Comment by barisusakli** [comment]
While trying to fix https://github.com/NodeBB/NodeBB/issues/4432

I figured out why this happens as well. See here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

If the second parameter to `.replace` has a special pattern then it means something else. For example `$$` inserts `$`. I got around it by not using a replacement function for the second param.

So instead of 
```
var a = '$$';
str = str.replace(str, a);
```

Use this
```
var a = '$$';
str = str.replace(str, function() { return a; });
```

Not sure in how many places you need to change this @psychobunny

**Comment by barisusakli** [comment]
Also related https://github.com/NodeBB/NodeBB/issues/2116

**Comment by barisusakli** [comment]
Seems to be fixed with above commit
